### ISSUE TITLE
test gives error

### ISSUE THREAD

**Issue by musicformellons** [markfinger/python-react#44]
When I run the test, I get:

(test3.4.3) MfM@MfM-XPS:~/TEST/python-react-master$ python runtests.py 

--------------------------------------------------------------------------------
Running tests without django
--------------------------------------------------------------------------------
E
======================================================================
ERROR: Failure: ConfigError (js-host binary /home/MfM/TEST/python-react-master/tests/node_modules/js-host/bin/js-host.js does not exist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/MfM/.pyenv/versions/3.4.3/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/MfM/.pyenv/versions/3.4.3/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/MfM/TEST/python-react-master/tests/__init__.py", line 8, in <module>
    js_host.conf.settings.configure(**JS_HOST)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/conf.py", line 60, in configure
    from .host import host
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/host.py", line 13, in <module>
    status = read_status_from_config_file(config_file)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/bin.py", line 16, in read_status_from_config_file
    cmd = (settings.PATH_TO_NODE, settings.get_path_to_bin(), config_file, '--config',)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/conf.py", line 94, in get_path_to_bin
    raise ConfigError('js-host binary {} does not exist'.format(path))
js_host.exceptions.ConfigError: js-host binary /home/MfM/TEST/python-react-master/tests/node_modules/js-host/bin/js-host.js does not exist

----------------------------------------------------------------------
Ran 1 test in 0.038s

FAILED (errors=1)

--------------------------------------------------------------------------------
Running tests with django
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 19, in <module>
    django.setup()
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/MfM/.pyenv/versions/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/models.py", line 7, in <module>
    **getattr(settings, 'JS_HOST', {})
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/conf.py", line 60, in configure
    from .host import host
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/host.py", line 13, in <module>
    status = read_status_from_config_file(config_file)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/bin.py", line 16, in read_status_from_config_file
    cmd = (settings.PATH_TO_NODE, settings.get_path_to_bin(), config_file, '--config',)
  File "/home/MfM/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/conf.py", line 94, in get_path_to_bin
    raise ConfigError('js-host binary {} does not exist'.format(path))
js_host.exceptions.ConfigError: js-host binary /home/MfM/TEST/python-react-master/tests/node_modules/js-host/bin/js-host.js does not exist

**Comment by markfinger** [comment]
Looks like the docs were out of date, but they should be correct now. The full set of commands is

```
pip install -r requirements.txt
cd tests
npm install
cd ..
python runtests.py
```

Once all the setup's fine, you only need to run `python runtests.py`

**Comment by musicformellons** [comment]
Did that but still get:
(test3.4.3) bom@bom-XPS:~/TEST/python-react-master$ python runtests.py

--------------------------------------------------------------------------------
Running tests without django
--------------------------------------------------------------------------------
E
======================================================================
ERROR: Failure: ValueError (Expecting value: line 1 column 1 (char 0))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/bom/TEST/python-react-master/tests/__init__.py", line 8, in <module>
    js_host.conf.settings.configure(**JS_HOST)
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/conf.py", line 60, in configure
    from .host import host
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/host.py", line 13, in <module>
    status = read_status_from_config_file(config_file)
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/bin.py", line 32, in read_status_from_config_file
    return json.loads(stdout)
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 0.040s

FAILED (errors=1)

--------------------------------------------------------------------------------
Running tests with django
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 19, in <module>
    django.setup()
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/models.py", line 7, in <module>
    **getattr(settings, 'JS_HOST', {})
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/conf.py", line 60, in configure
    from .host import host
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/host.py", line 13, in <module>
    status = read_status_from_config_file(config_file)
  File "/home/bom/.pyenv/versions/test3.4.3/lib/python3.4/site-packages/js_host/bin.py", line 32, in read_status_from_config_file
    return json.loads(stdout)
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/bom/.pyenv/versions/3.4.3/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by markfinger** [comment]
Yeah, it's strange.

I think #43's the root problem
