### ISSUE TITLE
basic_rendering example error 

### ISSUE THREAD

**Issue by hqman** [markfinger/python-react#57]
python example.py
  ```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from react.render import render_component
File "/Users/hqman/project/pydev/lib/python2.7/site-packages/react/render.py", line 2, in <module>
    from optional_django import staticfiles
  File "/Users/hqman/project/pydev/lib/python2.7/site-packages/optional_django/staticfiles.py", line 2, in <module>
    from .env import DJANGO_CONFIGURED
  File "/Users/hqman/project/pydev/lib/python2.7/site-packages/optional_django/env.py", line 20, in <module>
    getattr(DJANGO_SETTINGS, 'DEBUG', None)
  File "/Users/hqman/project/pydev/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/Users/hqman/project/pydev/lib/python2.7/site-packages/django/conf/__init__.py", line 40, in _setup
    raise ImportError("Settings cannot be imported, because environment variable %s is undefined." % ENVIRONMENT_VARIABLE)
ImportError: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
```

**Comment by markfinger** [comment]
Thanks for reporting that. Looks like a strange error, but django's always full of quirks.

The fix would be effect the line: https://github.com/markfinger/optional-django/blob/master/optional_django/env.py#L20

Would probably need to split the try/except again and catch an `ImportError` in another block.

@hqman can you run the following and report what it says:
```python
import django
print(django.VERSION)
```

**Comment by hqman** [comment]
>>> import django
>>> print(django.VERSION)
(1, 4, 10, 'final', 0)
>>>

**Comment by markfinger** [comment]
That's a fairly old and unsupported version of Django, so it may be exhibiting different behaviour than the later versions.

Can you try upgrading your django version and seeing if that fixes your issue? `pip install -U django`

For context, there's a compatibility layer that tries to detect if it's running in a django project, and then allows you to use relative paths that django magically resolves.

**Comment by hqman** [comment]
thanks @markfinger  it works

**Comment by hqman** [comment]
thanks @markfinger it works
