### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by Darwesh27** [markfinger/python-react#68]
Here is the error

```
Stack trace: SyntaxError: /home/junaid/work/savemyscope/frontend/js/app/containers/home.jsx: Unexpected token (83:12)
  81 |     render() {
  82 |         return (
> 83 |             <div>
     |             ^
  84 |                 <NavBar
  85 |                     navClass={this.state.navClass}
  86 |                     logo={this.state.logo}
    at Parser.pp.raise (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:517:12)
    at Parser.pp.parseExprSubscripts (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseParenAndDistinguishExpression (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:590:26)
    at Parser.pp.parseExprAtom (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:476:19)
    at Parser.pp.parseExprSubscripts (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExpression (/home/junaid/work/savemyscope/node_modules/babylon/lib/parser/expression.js:92:19)
```

And here is my `views.py`

```
from django.shortcuts import render
from react.render import render_component


def index(request):
    rendered = render_component('js/app/containers/home.jsx', {}, to_static_markup=True)
    print(rendered)
    return render(request, 'pages/rendered_index.html', {})

```

I don't know what going wrong here.

**Comment by markfinger** [comment]
That type of error comes up when babel is not being correctly applied to transform the code before execution. You need to add support for JSX to the babel compiler.

I'd recommend doing that by making changes to the `.babelrc` file: https://github.com/markfinger/python-react/blob/master/examples/basic_rendering/.babelrc

Make sure you've got support for jsx or a preset like `react`, https://babeljs.io/docs/plugins/preset-react/
