### ISSUE TITLE
basic_rendering example - TypeError: a float is required

### ISSUE THREAD

**Issue by mplis** [markfinger/python-react#80]
I'm seeing this traceback when trying to run the basic_rendering example. I'm using python 2.7.11 and node 6.9.1

```
Traceback (most recent call last):
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/example.py", line 20, in index
    to_static_markup=True,
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/react/render.py", line 17, in render_component
    return renderer.render(path, props, to_static_markup, request_headers, timeout=timeout)
  File "/Users/mplis/personal/misc/python-react/examples/basic_rendering/venv/lib/python2.7/site-packages/react/render_server.py", line 58, in render
    timeout=timeout
  File "/Users/mplis/workspace/main/tools/python/modules/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/Users/mplis/workspace/main/tools/python/modules/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/mplis/workspace/main/tools/python/modules/requests/sessions.py", line 354, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mplis/workspace/main/tools/python/modules/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mplis/workspace/main/tools/python/modules/requests/adapters.py", line 211, in send
    timeout=timeout
  File "/Users/mplis/workspace/main/tools/python/modules/requests/packages/urllib3/connectionpool.py", line 428, in urlopen
    body=body, headers=headers)
  File "/Users/mplis/workspace/main/tools/python/modules/requests/packages/urllib3/connectionpool.py", line 280, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 563, in create_connection
    sock.settimeout(timeout)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: a float is required
```

**Comment by markfinger** [comment]
Looks like requests is passing the render server's timeout down to the stdlib's socket lib, and it's complaining about the type passed in.

The timeout's default value is defined at https://github.com/markfinger/python-react/blob/master/react/render_server.py#L48-L50. According to request's docs (http://docs.python-requests.org/en/master/user/advanced/#timeouts) it's in a valid form though.

@mplis can you: 
- run `pip freeze` and paste the output here. I'm mostly interested in which version of `requests` you have installed.
- can you replace the content of https://github.com/markfinger/python-react/blob/master/react/render_server.py#L50 with `timeout = 5.0` and see if that fixes it?

If that fixes it, do you mind making a PR with that change? It's sufficiently small, that you should be able to just use github's in-browser editor.

**Comment by mplis** [comment]
Changing the timeout fixed the problem. I've submitted a PR [here](https://github.com/markfinger/python-react/pull/81).

Also, here's the output of `pip freeze` in case you were still wondering:

```
-> % pip freeze
Flask==0.10.1
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
optional-django==0.3.0
react==4.1.0
requests==2.7.0
Werkzeug==0.12.2
```

**Comment by markfinger** [comment]
Thanks for the PR

**Comment by markfinger** [comment]
I've pushed `4.1.1` to pypi, with your patch.

Thanks again.
